// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfqS72hO2pqQIgQJWAKanXhzGcNXrAhA',
    appId: '1:279123730825:web:6b8fbfc4bb3aca3aa94158',
    messagingSenderId: '279123730825',
    projectId: 'traamp-app',
    authDomain: 'traamp-app.firebaseapp.com',
    storageBucket: 'traamp-app.firebasestorage.app',
    measurementId: 'G-Y5R28L9CRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqy8KIR-u8lxn89RVs5EqwR5H_AOKVp4',
    appId: '1:279123730825:android:cf2de4f30ac34386a94158',
    messagingSenderId: '279123730825',
    projectId: 'traamp-app',
    storageBucket: 'traamp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqDB1TlIMApz8-29Uau67vCDr5IBUPVM',
    appId: '1:279123730825:ios:291f38c9546f7132a94158',
    messagingSenderId: '279123730825',
    projectId: 'traamp-app',
    storageBucket: 'traamp-app.firebasestorage.app',
    iosBundleId: 'com.example.traampFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxqDB1TlIMApz8-29Uau67vCDr5IBUPVM',
    appId: '1:279123730825:ios:291f38c9546f7132a94158',
    messagingSenderId: '279123730825',
    projectId: 'traamp-app',
    storageBucket: 'traamp-app.firebasestorage.app',
    iosBundleId: 'com.example.traampFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKfqS72hO2pqQIgQJWAKanXhzGcNXrAhA',
    appId: '1:279123730825:web:083433743ed64408a94158',
    messagingSenderId: '279123730825',
    projectId: 'traamp-app',
    authDomain: 'traamp-app.firebaseapp.com',
    storageBucket: 'traamp-app.firebasestorage.app',
    measurementId: 'G-HJKQCKWED9',
  );
}